# In General Get conda on "https://repo.anaconda.com/miniconda/"
# ON Linux: run "wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
# Conda environment file for Master Thesis 2D Electronic Spectroscopy project
# Usage: conda env create -f environment.yml
# Update: conda env update -f environment.yml

name: master_env
channels:
  - conda-forge  # Preferred channel for scientific packages
  - defaults

dependencies:
  # Core Python
  - python=3.11
  - pip
  
  # Conda packages (when available, prefer conda over pip)
  - numpy>=1.20.0,<3.0.0  # Compatible with matplotlib 3.10+
  - scipy>=1.7.0
  - matplotlib>=3.10.0    # Required for NumPy 2.x compatibility
  - qutip>=5.2.0
  - psutil>=5.8.0
  # - pickle-mixin>=1.0.2 TODO uncomment on windows, not available on Linux
  - joblib>=1.1.0
  - jupyter
  - ipython
  - black>=22.0.0  # code formatter (extras not supported in conda specs)
  - mpmath
  - pytest>=7.0.0
  - tqdm>=4.64.0            # Progress bar for loops
  - pip:
    - -e ./code/python            # installs project_config (local project utils)
    - -e ./external/qspectro2d    # qspectro2d package (submodule)
    - -e ./external/plotstyle     # plotting style (submodule)