# In General Get conda on "https://repo.anaconda.com/miniconda/"
# ON Linux: run "wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
# Conda environment file for Master Thesis 2D Electronic Spectroscopy project
# Usage: conda env create -f environment.yml
# Update: conda env update -f environment.yml

name: master_env
channels:
  - conda-forge  # Preferred channel for scientific packages
  - defaults

dependencies:
  # Core Python
  - python=3.11
  - pip
  
  # Conda packages (when available, prefer conda over pip)
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - qutip>=5.2.0
  - psutil>=5.8.0
  # - pickle-mixin>=1.0.2 TODO uncomment on windows, not available on Linux
  - joblib>=1.1.0
  - jupyter
  - ipython
  - black[jupyter]>=22.0.0 # just my preference, also install black for python formatting?
  - mpmath
  - multiprocessing
  - pip
  - json
  - pip:
    - -e ./code/python       # Local package in editable mode
    - tqdm                  # Progress bar for loops
