# qspectro2d run configuration (merges over defaults)
# Place in the scripts directory next to calc_datas.py

atomic:
  # TODO
  # if n_atoms = 1 -> put
  # frequencies_cm: [16000.0]
  # dip_moments: [1.0]

  # if n_atoms = 2 and coupling_cm = 0 -> put these
  # frequencies_cm: [15640.0, 16360.0]
  # dip_moments: [1.0, 1.0]
  # if additionally coupling_cm == 300 -> do
  # frequencies_cm: [15800.0, 16200.0]
  # dip_moments: [-0.23, 1.0]

  n_atoms: 1
  frequencies_cm: [16000.0]
  n_inhomogen: 1
  delta_inhomogen_cm: 0.0
  dip_moments: [1.0]
  n_chains: 1
  max_excitation: 2

laser:
  pulse_fwhm_fs: 5.0
  envelope_type: gaussian
  carrier_freq_cm: 16000.0
  rwa_sl: true

bath:
  bath_type: ohmic
  cutoff: 100       # actually in terms of frequency
  temperature: 1e-6    # actually in terms of frequency
  coupling: 0.01   # actually in terms of frequency

config:
  solver: ME

window:
  t_det_max: 60.0
  t_wait: 10.0
  t_coh: 3.0
  dt: 2.0