# qspectro2d run configuration (merges over defaults)
# Place in the scripts directory next to calc_datas.py

atomic:
  n_atoms: 2
  n_chains: 1
  frequencies_cm: [16000.0, 16000.0]#, 17000.0]#, 15950.0, 16050.0, 16000.0]
  dip_moments: [1.0, 1.0]#, 1.0]#, 1.0, 1.0, 1.0]
  coupling_cm: 200.0
  delta_cm: 0.0
  max_excitation: 1
  n_freqs: 1

laser:
  pulse_fwhm_fs: 5.0
  base_amplitude: 0.5
  envelope_type: gaussian
  carrier_freq_cm: 16000.0
  rwa_sl: false

bath:
  bath_type: ohmic
  temperature: 1    # actually in terms of frequency
  cutoff: 100       # actually in terms of frequency
  coupling: 0.001   # actually in terms of frequency

solver:
  solver: BR
  solver_options:
    nsteps: 200000
    atol: 1.0e-7
    rtol: 1.0e-5

window:
  # parameters that can be adjusted in the cli args of calc_datas.py
  t_wait: 0.0
  dt: 10.0
  t_det_max: 800.0
  # 2d params
  t_coh: 0.0
  #
  n_batches: 10
  batch_idx: 0